### ISSUE TITLE
Cannot reproduce the example

### ISSUE THREAD

**Issue by Shen-Jing** [lkuchenb/hmmer2pdf#5]
Hello, 

I'm sorry to disturb you again.

After I solve the issue #1, I encounter another difficulty:

```
Reading HMM file... Done.
LaTeX Conversion... Done.
Compiling...
ERROR - LaTeX compiler failed. You may want to inspect the .log and .tex files in
/tmp/tmpi7j_dlks
```

#### Environment

- Python: 3.7.7
- LaTeX (`latex --version`)
  - pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016)
  - kpathsea version 6.2.2
- LuaTeX: Version 0.95.0 (TeX Live 2016)

The log file is 500 lines.
How could I provide clues that will help you?

Thank you.

**Comment by lkuchenb** [comment]
It would be helpful to zip that folder and attach it to the issue. You can just drag + drop the zip file into the comment editor. Thanks!

**Comment by lkuchenb** [comment]
If sharing the `.tex` file (and therefore also the HMM) here is not an option for you, feel free to email me or reproduce the error on a toy example.

**Comment by Shen-Jing** [comment]
Amazing response speed.

It is thoughtful of you, thank you!

I executed same command at `hmmer2pdf/examples/`.
This is my logging folder: 
[log.zip](https://github.com/lkuchenb/hmmer2pdf/files/5424435/log.zip)

Thanks for your time!

**Comment by lkuchenb** [comment]
That seems to be an issue with the old texlive (and thus `lualatex`) version. It would be best if you would update to a recent texlive release.

For small HMMs, you could try if `pdflatex` works for you. Simply run

```
latexmk -c hmm
latexmk -pdf hmm
```

inside the temporary folder that is reported in the error message and check if the `hmm.pdf` file looks okay. However, `pdflatex` will fail for larger alignments.

**Comment by Shen-Jing** [comment]
Now it works!

First, sorry I misunderstood that my texlive installed from the package manager (Fedora 31) would be the latest version.

The solution of small HMMs also work in my older environment.

Thank you very much!

**Comment by lkuchenb** [comment]
You're welcome. I've added a switch `--pdflatex` to enable pdflatex instead of lualatex in the backend. But that really will only work for small HMMs. It would be best to get a recent texlive version.
