### ISSUE TITLE
Required latex packages

### ISSUE THREAD

**Issue by multimeric** [lkuchenb/hmmer2pdf#8]
Hi, thanks for making this utility.
It seems that, in addition to the stated dependencies, you also need the following packages within your latex distribution:

* `tikz`
* `standalone`

On Ubuntu/Debian , you therefore need the following packages: `texlive texlive-latex-extra texlive-luatex`. It might be helpful to mention this somewhere in the readme.

**Comment by lkuchenb** [comment]
Thanks, I've added that to the README
